version: "3.9"  # optional since v1.27.0
services:
  nginx_test:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - static-files:/home/django_test/static
    networks:
      - network
  django_test:
    build: django
    ports: 
      - "8000:8000"
    networks:
      - network
    volumes:
      - static-files:/home/django_test/static
volumes:
  static-files:

networks:
  network:
    name: net1
