version: "3.9"  # optional since v1.27.0
services:
  nginx_test:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - static-back:/home/django_test/static
      - static-front:/usr/app/public/assets
    networks:
      - network
  django_test:
    build: django
    expose: 
      - "8000"
    networks:
      - network
    volumes:
      - static-back:/home/django_test/static
  next_test:
    build: next.js
    expose: 
      - "7000"
    networks:
      - network
    volumes:
      - static-front:/usr/app/public/assets
volumes:
  static-front:
  static-back:

networks:
  network:
    name: net1
