# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox"

  config.vm.define "test" do |test|
    test.vm.box = "generic/ubuntu2010"

    test.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      #vb.network "private_network", ip: "192.168.33.10"
      #vb.hostname = "test.server"
    end
  end

  config.vm.define "qa" do |qa|
    qa.vm.box = "generic/ubuntu2010"

    qa.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      #vb.network "private_network", ip: "192.168.33.11"
      #vb.hostname = "qa.server"
    end
  end

  config.vm.define "production" do |production|
    production.vm.box = "generic/ubuntu2010"

    production.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      #vb.network "private_network", ip: "192.168.33.12"
      #vb.hostname = "production.server"
    end
  end
 
  config.vm.define "admin" do |admin|
    admin.vm.box = "generic/ubuntu2010"

    admin.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      #vb.network "private_network", ip: "192.168.33.13"
      #vb.hostname = "admin.server"
    end
  end 

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

end
