# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder "../", "/app"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.define "admin" do |admin|
    #admin.vm.box = "generic/ubuntu2010"
    admin.vm.box = "ubuntu/xenial64"
    admin.vm.hostname = "admin"
    admin.vm.network "private_network", ip: "192.168.33.13"
    admin.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
    admin.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "admin.yml"
      ansible.extra_vars = {
        #ansible_python_interpreter:"/usr/bin/python3"
        node_ip: "192.168.33.13"
      }
    end
  end 

  config.vm.define "test" do |test|
    test.vm.box = "ubuntu/xenial64"
    test.vm.hostname = "test"
    test.vm.network "private_network", ip: "192.168.33.10"
    test.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
    test.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "node.yml"
      ansible.extra_vars = {
        node_ip: "192.168.33.10"
      }
    end
  end

  config.vm.define "qa" do |qa|
    qa.vm.box = "ubuntu/xenial64"
    qa.vm.hostname = "qa"
    qa.vm.network "private_network", ip: "192.168.33.11"
    qa.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
    qa.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "node.yml"
      ansible.extra_vars = {
        node_ip: "192.168.33.11"
      }
    end
  end

  config.vm.define "production" do |production|
    production.vm.box = "ubuntu/xenial64"
    production.vm.hostname = "production"
    production.vm.network "private_network", ip: "192.168.33.12"
    production.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
    end
    production.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "node.yml"
      ansible.extra_vars = {
        node_ip: "192.168.33.12"
      }
    end 
 end
 
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

end
