apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: static-db
  name: static-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
status: {}
